baseURL = "https://bncling.github.io/"
languageCode = "en-us"
title = "Ben Clingenpeel"

theme = "hugo-paper"

[menu]

	[[menu.main]]
	name = "Posts"
	identifier = "posts"
	url = "/posts/"

	[[menu.main]]
	name = "Math Wikis"
	identifier = "math-wikis"
	url = "/math-wiki/"

	[[menu.main]]
	name = "Tags"
	identifier = "tags"
	url = "/tags/"

	[[menu.main]]
	name = "About"
	identifier = "about"
	url = "/about"

	[[menu.main]]
	name = "Animations"
	identifier = "animations"
	url = "/animations/"

[markup]
	defaultMarkdownHandler = "pandoc"

[taxonomies]
	tag = "tags"